stages:
  - static_analysis
  - test
  - build
  - deploy
  - security

cache:
  key: "$CI_REPOSITORY_URL"

before_script:
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_ALL=en_US.UTF-8

"static_analysis:swiftlint":
  stage: static_analysis
  before_script:
    - /bin/bash $CACHE_DIR/bundlerScript.bash
  only:
    - branches
    - merge_requests
    - tags
  tags:
    - xcode-12.2
  script:
    - bundle exec fastlane lint

# Disabled for Polidea CI
#"build:debug":
#  stage: build
#  before_script:
#    - /bin/bash $CACHE_DIR/bundlerScript.bash
#  only:
#    - refs
#    - branches
#    - merge_requests
#  tags:
#    - xcode-12.2
#  script:
#    - bundle exec fastlane build,

"testUnit:debug":
  stage: test
  before_script:
    - /bin/bash $CACHE_DIR/bundlerScript.bash
  only:
    - branches
    - merge_requests
    - tags
  tags:
    - xcode-12.2
  script:
    - bundle exec fastlane unitTests
  artifacts:
    expire_in: 1 day
    paths:
      - fastlane/test_output/xctest/report.junit
      - fastlane/test_output/xctest/report.html
    reports:
      junit: fastlane/test_output/xctest/report.junit

"testUI:debug":
  stage: test
  before_script:
    - /bin/bash $CACHE_DIR/bundlerScript.bash
  tags:
    - xcode-12.2
  script:
    - bundle exec fastlane UiTests
  only:
    - merge_requests
    - tags
  artifacts:
    expire_in: 2 day
    paths:
      - fastlane/test_output/xctest/report.junit
      - fastlane/test_output/xctest/report.html
    reports:
      junit: fastlane/test_output/xctest/report.junit

"deploy:debug":
  stage: deploy
  before_script:
    - /bin/bash $CACHE_DIR/bundlerScript.bash
  tags:
    - xcode-12.2
  only:
    - tags
  script:
    - bundle exec fastlane deploy

"security:owasp_dependency_check":
  stage: security
  image:
    name: owasp/dependency-check
    entrypoint: [""]
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh --project "Passbolt PoC" --scan Podfile.lock --enableExperimental  -f XML -f HTML --out .
  artifacts:
    expire_in: 1 day
    paths:
      - dependency-check-report.xml
      - dependency-check-report.html
    reports:
      junit: dependency-check-report.xml
  tags:
    - docker
  only:
    refs:
      - merge_requests
    changes:
      - Podfile
      - Podfile.lock

"security:owasp_dependency_check_tag":
  stage: security
  image:
    name: owasp/dependency-check
    entrypoint: [""]
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh --project "Passbolt PoC" --scan Podfile.lock --enableExperimental  -f XML -f HTML --out .
  artifacts:
    expire_in: 1 day
    paths:
      - dependency-check-report.xml
      - dependency-check-report.html
    reports:
      junit: dependency-check-report.xml
  tags:
    - docker

