# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    xcversion(version: "12.2")
  end

  lane :lint do
    swiftlint(
      executable: "Pods/SwiftLint/swiftlint"
    )
  end

  def kill_simulators
    Action.sh("killall -9 Simulator 2>/dev/null || echo No simulators running")
  end
  
  test_device = "iPhone 11"

  lane :unitTests do
    desc "Run unit tests"
    kill_simulators
    clear_derived_data
    scan(
      workspace: "Passbolt POC.xcworkspace",
      device: test_device,
      scheme: "Passbolt POC",
      testplan: "UnitTest",
      output_types: 'html,junit',
      output_directory: './fastlane/test_output/xctest'
    )
  end

  lane :UiTests do
    desc "Run UI tests"
    kill_simulators
    clear_derived_data
    cocoapods(
      clean_install: true
    )
    scan(
      workspace: "Passbolt POC.xcworkspace",
      device: test_device,
      scheme: "Passbolt POC",
      testplan: "UITest",
      output_types: 'html,junit',
      output_directory: './fastlane/test_output/xctest'
    )
  end

  desc "Build debug version"
  lane :build do
    gym(scheme: "Passbolt POC")
  end

  desc "Deploy debug version"
  lane :deploy do
    gym(scheme: "Passbolt POC")
    # pilot or upload_to_testflight or firebase_app_distribution or deploy_shuttle
  end

end
